### ISSUE TITLE
Cant build the code

### ISSUE THREAD

**Issue by Sogokong** [andrew-r-king/sfml-vscode-boilerplate#1]
I have been following your tutorial but when trying to build it i get this error message.

```
bash : The term 'bash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,
or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ bash ./build.sh buildrun Release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (bash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I unistalled my minGW which i self had instaled and tried to use the minGW which you provided but no luck.

**Comment by andrew-r-king** [comment]
What platform are you on? 
Assuming Windows, which terminal are you using? I built this around git bash for windows, and the settings.json uses "C:/Program Files/Git/bin/bash.exe" for the terminal's path. 

Other paths:
SFML: C:/SFML-2.5.1/bin
MinGW: C:/mingw32/bin

And yes, use the MinGW version provided (7.3.0). 8.1.0 had a critical bug in std::filesystem last time I checked, so I've been waiting for their next update (whenever that may be). You can easily set this up with a different compiler with some configuration tweaks.

**Comment by andrew-r-king** [comment]
Oh and make sure you "open with code" in the sfml-vscode-boilerplate folder if you aren't already doing that. That might be issue too if it's not picking up the settings.json.

**Comment by Sogokong** [comment]
I'm using windows 10 64x. I did open the folder in VS code. Do I have to add the minGW and SFML you are providing to path?

**Comment by andrew-r-king** [comment]
The settings.json basically makes it a closed environment, so you shouldn't have to add anything to your PATH variable. Just make sure you have SFML 2.5.1 & mingw-w64 (the one in the readme) and they're installed to those paths I mentioned above.

The bigger problem is that you can't event get the bash script to run, so that tells me that you don't have git installed and the command is running from powershell. Get it here & install it with all of the default options: https://git-scm.com/download/win.

That's required so that the project can be cross-platform. By default, vscode on windows uses powershell (which doesn't read bash scripts), hence your error.

**Comment by gabjohn** [comment]
I followed your tutorial but after ctrl+shift+b there is an error.

src/PCH.hpp
process_begin: CreateProcess(NULL, i686-w64-mingw32-g++.exe -MT bin/Debug/obj/PCH.hpp.gch -MMD -MP -MF bin/Debug/dep/PCH.Td -D_DEBUG -g -Og -Wfatal-errors -Wunreachable-code -Wextra
-Wall -std=c++17 -fdiagnostics-color=always -pg -Isrc/ -IC:/SFML-2.5.1/include -o bin/Debug/obj/PCH.hpp.gch -c src/PCH.hpp, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:219: recipe for target 'bin/Debug/obj/PCH.hpp.gch' failed
mingw32-make[1]: *** [bin/Debug/obj/PCH.hpp.gch] Error 2
mingw32-make[1]: Target 'makepch' not remade because of errors.
Makefile:178: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
