### ISSUE TITLE
./build.sh: line 201:   872 Segmentation fault      bin/$BUILD/$NAME $OPTIONS

### ISSUE THREAD

**Issue by LionasBaslis2sis** [andrew-r-king/sfml-vscode-boilerplate#12]
I get this error when I try to Build & Run : Debug my project : ./build.sh: line 201:   872 Segmentation fault      bin/$BUILD/$NAME $OPTIONS

**Comment by andrew-r-king** [comment]
Well, you have a segmentation fault in your program, first of all, so in case you're asking about that: https://en.wikipedia.org/wiki/Segmentation_fault

Otherwise, the error output itself coming from the build script could be a little cleaner. I don't like how it's spitting out "./build.sh: line 201" and "bin/$BUILD/$NAME $OPTIONS"
