### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by gabjohn** [andrew-r-king/sfml-vscode-boilerplate#4]
After build & run, the output is this.

src/PCH.hpp
process_begin: CreateProcess(NULL, i686-w64-mingw32-g++.exe -MT bin/Debug/obj/PCH.hpp.gch -MMD -MP -MF bin/Debug/dep/PCH.Td -D_DEBUG -g -Og -Wfatal-errors -Wunreachable-code -Wextra
-Wall -std=c++17 -fdiagnostics-color=always -pg -Isrc/ -IC:/SFML-2.5.1/include -o bin/Debug/obj/PCH.hpp.gch -c src/PCH.hpp, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:219: recipe for target 'bin/Debug/obj/PCH.hpp.gch' failed
mingw32-make[1]: *** [bin/Debug/obj/PCH.hpp.gch] Error 2
mingw32-make[1]: Target 'makepch' not remade because of errors.
Makefile:178: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by andrew-r-king** [comment]
That error is caused by make not finding "i686-w64-mingw32-g++.exe" (but correctly finds mingw32-make.exe). What version of mingw are you using?

If you're using a different one that's recommended in the readme, all you need to do is set the CC variable in env/windows.all.mk:

```
CC := i686-w64-mingw32-g++.exe
```

Change that to the g++.exe with the correct prefix.
