### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by pedzed** [andrew-r-king/sfml-vscode-boilerplate#7]
It would be nice to have a way to unit test. Either Catch2 or Google.Test would be great.

**Comment by andrew-r-king** [comment]
Very true! It's been in the back of my brain, but I haven't had a great reason to add it until now.

I'll look into testing strategies with SFML (probably with Catch2). I think it'll ultimately mean a "tests" folder that sits alongside src, since everything in src is automatically picked up in the main target's compile, but I'll have to add a bunch of things to the makefile (maybe make it finally support multiple build targets).

**Comment by pedzed** [comment]
That would be great, because that's currently what's stopping me from using this amazing boilerplate.

In my current setup (wanting to add SFML very soon), I have:
```
/bin (VCS ignored, compiled binaries)
/lib (external libraries)
-- / Catch2
-- -- /catch.hpp
/src
-- main.cpp
-- ExampleClass.h
-- ExampleClass.cpp
-- ...
/test
-- main.cpp
-- test_ExampleClass.cpp
Makefile
```

In `test/main.cpp`, I have:
```cpp
#define CATCH_CONFIG_MAIN
#include <Catch2/catch.hpp>
```
Just like explained in the docs.

In `test/test_ExampleClass.cpp`:
```cpp
#include <Catch2/catch.hpp>
#include <ExampleClass.h>

TEST_CASE("Test") {
    //
}
```

And of course my Makefile:
```Makefile
.PHONY: test run clean

CXX		  := g++
CXX_FLAGS := -Wall -Wextra -std=c++17 -ggdb

BIN		:= bin
SRC		:= src
INCLUDE	:= include
LIB		:= lib
TEST	:= test

LIBRARIES	:=
MAIN_EXEC	:= $(BIN)/main

TEST_OBJS	:= \
	$(TEST)/main.cpp \
	$(filter-out $(SRC)/main.cpp, $(wildcard $(SRC)/*.cpp))
TEST_EXEC	:= $(BIN)/run_test

all: $(MAIN_EXEC)

test: $(TEST_OBJS)
	@$(CXX) \
		$(CPP_FLAGS) \
		-I$(LIB) \
		-I$(SRC) \
		-I$(TEST) \
		-o$(TEST_EXEC) \
		$(TEST_OBJS) \
		$(TEST_SRC)
	@./$(TEST_EXEC)

run: clean all
	clear
	./$(MAIN_EXEC)

$(MAIN_EXEC): $(SRC)/*.cpp
	$(CXX) $(CXX_FLAGS) -I$(INCLUDE) -L$(LIB) $^ -o $@ $(LIBRARIES)

clean:
	-rm $(BIN)/*
```
The Makefile is quite a mess, but I was so happy when it worked (I smashed two examples together, with some Stack Overflow-ing).

**Comment by andrew-r-king** [comment]
Great write up! That makes adding it a lot easier. I created a unit-testing branch already, but it might take me a few days before it's done.

**Comment by andrew-r-king** [comment]
It's been added! Do you mind reviewing the unit-testing branch and letting me know if there's any issues/questions/concerns with it? If not, I'll merge it into master.

There's a "Tests" build target that you can configure separately from Release/Debug. It's built with the "Build & Run: Tests" task.

**Comment by pedzed** [comment]
I'm scratching my head a bit. Did you break anything after your comment?

I don't see any Makefile for tests.

![image](https://user-images.githubusercontent.com/8146593/62423691-04b00300-b6c4-11e9-8f9d-96c68ed0fd78.png)

Should I not expect 92270b1e30bc534becbd309e85df1d3658233fe0 (`/env/.tests.mk`) to be there?

**Comment by andrew-r-king** [comment]
There is no "Makefile for tests". Open the repo in vscode & use the task runner to find the "Build & Run: Tests" task. That paret hasn't changed.

I continued to mess with it though. I was annoyed that "Tests" was building basically a copy of Release in addition to the unit tests, so I basically rolled them together. The tests builds a ".tests" folder inside "bin/Release" in addition to a second .exe anyway. There's a number of ways to do this, but this seemed like an okay approach without building duplicate object files, and it also minimized the amount of code added to the Makefile.  

Some of the other commits are related to fixing things that broke on MacOS.

just pull in the latest changes in that branch, remove the existing bin/build, and run through the different build tasks.

**Comment by pedzed** [comment]
Ah, yes. It does seem to work on Ubuntu with `sudo apt install sfml-dev`.
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
I will also try it on Windows 10 when I get to it. Perhaps also on macOS, but probably not soon (unless you really need a tester).

**Comment by pedzed** [comment]
Is it possible to add buttons to the statusbar?

![SFML in VSCode](https://user-images.githubusercontent.com/8146593/62427697-18289180-b6f7-11e9-89f1-4eba7b21cb32.png)

**Comment by andrew-r-king** [comment]
Not without writing an actual extension (which is the beyond scope of this project). I could add a keybinding for it in the _keybindings.json file, but there's still the manual step of copying the keybindings yourself.

**Comment by pedzed** [comment]
What about `launch.json`? https://code.visualstudio.com/docs/editor/debugging

**Comment by andrew-r-king** [comment]
You're kind of talking about 2 separate things now. The boilerplate already includes a launch.json (hidden by default via settings.json), and it's just for configuring/launching the GDB/LLDB debugger, which depends on the "Build & Run: Debug" task. GDB is the debugger executable on windows & linux, while LLDB is the mac one. Despite its name, launch.json isn't just a "launcher" if that makes sense. It's meant for launching debugger configurations.

So a realistic scenario would be, instead of building the tests alongside the Release build, I could set to the Debug build and make a second configuration in launch.json that will launch the tests, and you could also step through via the debugger. It's admittedly slightly more useful than building it with the Release configuration, but if you find yourself needing to debug your unit test code, you've maybe gone astray... If a unit tests fails, it'll tell you exactly which one failed anyway. 

Again, I would just use a keybinding for the task if you want to launch it often. (F9 & F10 build & run Release/Debug respectively).

**Comment by pedzed** [comment]
> Again, I would just use a keybinding for the task if you want to launch it often. (F9 & F10 build & run Release/Debug respectively).

Sometimes I teach people. It's not always feasible to make people remember keybindings. I know it's slightly out of the scope of a boilerplate, but since `.vscode/*` is already customized, if it is possible, why not add two buttons as well, I'd say?

> The boilerplate already includes a launch.json (hidden by default via settings.json)

Oh, God! Why would anybody do that? Haha, the funny thing is that I saw that on Windows. Completely forgot about it.

Anyway, I'm trying to find an extension that allows for custom buttons, but I can't quickly find any. 

I think I rather abuse the debug buttons than use keybindings. I had such an odd setup on Windows and quite liked it.

**Comment by andrew-r-king** [comment]
> Oh, God! Why would anybody do that? 

The point is really so one can focus on their code rather than the build system. The only reason you'd have to go into either tasks.json, launch.json, build.sh, or the Makefile is to modify the way your program builds. The full list of exclusions is in "files.exclude" in settings, which you can obviously modify.

But yeah, in order to do buttons, you basically have to write Typescript, node.js and read up about vscode's Extension API. I found it was easier to memorize Ctrl+Shift+B :)

**Comment by andrew-r-king** [comment]
I've merged this to master (as well as fixed some issues with the MacOS debugger & app bundle).
